// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyfdNBOkIVHtlut3dKhXqpUmigSdNRvfg',
    appId: '1:418044323270:web:7f046471c19cfa89c97ec7',
    messagingSenderId: '418044323270',
    projectId: 'smart-fire-robot',
    authDomain: 'smart-fire-robot.firebaseapp.com',
    storageBucket: 'smart-fire-robot.firebasestorage.app',
    measurementId: 'G-NEJM3KMTQJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAez9z_vx02Xqi2rA01XrYQdc-OqSZdr3U',
    appId: '1:418044323270:android:474bb441e1e33934c97ec7',
    messagingSenderId: '418044323270',
    projectId: 'smart-fire-robot',
    storageBucket: 'smart-fire-robot.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZOvX1BPoaTcbWBZ6imVTx7r2E1rekOcU',
    appId: '1:418044323270:ios:461e121daffe6ae0c97ec7',
    messagingSenderId: '418044323270',
    projectId: 'smart-fire-robot',
    storageBucket: 'smart-fire-robot.firebasestorage.app',
    iosBundleId: 'com.example.smartFireRobot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZOvX1BPoaTcbWBZ6imVTx7r2E1rekOcU',
    appId: '1:418044323270:ios:461e121daffe6ae0c97ec7',
    messagingSenderId: '418044323270',
    projectId: 'smart-fire-robot',
    storageBucket: 'smart-fire-robot.firebasestorage.app',
    iosBundleId: 'com.example.smartFireRobot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyfdNBOkIVHtlut3dKhXqpUmigSdNRvfg',
    appId: '1:418044323270:web:42401956a5e9833fc97ec7',
    messagingSenderId: '418044323270',
    projectId: 'smart-fire-robot',
    authDomain: 'smart-fire-robot.firebaseapp.com',
    storageBucket: 'smart-fire-robot.firebasestorage.app',
    measurementId: 'G-5TPECTCBYW',
  );
}
